OrdererOrgs:
  - Name: orderer
    Domain: orderer.com
    EnableNodeOUs: true
    Specs:
        - Hostname: orderer
        - Hostname: orderer1
        - Hostname: orderer2
        - Hostname: orderer3
        - Hostname: orderer4